-- Run these SQL commands in Snowflake if needed
DROP STAGE IF EXISTS TFDB.DEV.snowflake_internal_stage;
DROP SCHEMA IF EXISTS TFDB.DEV;
DROP WAREHOUSE IF EXISTS DEV_WH;
DROP ROLE IF EXISTS DEV_ROLE;
DROP DATABASE IF EXISTS TFDB;
