# .github/workflows/terraform.yml

name: Deploy Snowflake Database with Terraform

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -var="snowflake_account=${{ secrets.SNOWFLAKE_ACCOUNT }}" \
                               -var="snowflake_username=${{ secrets.SNOWFLAKE_USERNAME }}" \
                               -var="snowflake_password=${{ secrets.SNOWFLAKE_PASSWORD }}" \
                               -var="snowflake_region=${{ secrets.SNOWFLAKE_REGION }}" \
                               -var="database_name=${{ secrets.DATABASE_NAME }}"

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var="snowflake_account=${{ secrets.SNOWFLAKE_ACCOUNT }}" \
                                                 -var="snowflake_username=${{ secrets.SNOWFLAKE_USERNAME }}" \
                                                 -var="snowflake_password=${{ secrets.SNOWFLAKE_PASSWORD }}" \
                                                 -var="snowflake_region=${{ secrets.SNOWFLAKE_REGION }}" \
                                                 -var="database_name=${{ secrets.DATABASE_NAME }}"

