name: 'Terraform Snowflake Infra Setup'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  terraform:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Install SnowSQL
      run: |
        curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
        SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
        echo "~/snowflake" >> $GITHUB_PATH 

    - name: Configure SnowSQL
      env:
        SNOWSQL_ACCOUNT: gxkmoso-pb31214 
        SNOWSQL_USER:  SANJAY
        SNOWSQL_PWD:  Temp@123$ 
      run: |
        mkdir -p ~/.snowsql
        cat > ~/.snowsql/config << EOF
        [connections.default]
        accountname = $SNOWSQL_ACCOUNT
        username = $SNOWSQL_USER
        password = $SNOWSQL_PWD
        EOF

    - name: Verify SnowSQL installation
      run: snowsql -v  

    - name: Run SnowSQL Command
      run: snowsql -c my_connection
     
          
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="variables.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="variables.tfvars"
