name: 'Terraform Snowflake Infra Setup'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  terraform:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

        
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="variables.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="variables.tfvars"
